### ISSUE TITLE
nutanix_vm: rename nic_list parameters

### ISSUE THREAD

**Issue by yannickstruyf3** [ideadevice/ansible-ahv-provider-plugin#21]
nic_list has one attribute: `uuid` but this should be renamed to `subnet`. This will bring it more in line with the `cluster` attribute that also accepts uuid or name

**Comment by saratkumar-yb** [comment]
Fixed.

**Comment by saratkumar-yb** [comment]
with change in nic structure similar to V3 spec no we have separate uuid and name fields
